config/routes.rb
MusicApp::Application.routes.draw do
  resources :users
  resource :sessions
  resources :bands
  resources :albums
  resources :tracks

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many(
  :tracks,
  :class_name => "Track",
  primary_key: :id,
  foreign_key: :album_id,
  before_destroy :dependent => :destroy
  )

  belongs_to(
  :band,
  :class_name => "Band",
  primary_key: :id,
  foreign_key: :band_id
  )

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessor :name
  has_many(
    :albums,
    :class_name => "Album",
    primary_key: :id,
    foreign_key: :album_id
   # before_destroy :dependent => :destroy
  )
  before_destroy :dependent => :destroy
  validates :name, presence: true
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to(
    :album,
    :class_name => "Album",
    primary_key: :id,
    foreign_key: :id
  )

end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  include BCrypt
  attr_reader :password

  after_initialize do |user|
    user.ensure_session_token
  end

  validates :email_address, presence: true
  validates :password_digest, presence: true
  validates :password, :length => {minimum: 1, :allow_nil => true}


  def self.find_by_credentials(email, password)
    matching_users = []
    User.all.each do |user|
      pswords_match = user.is_password?(password)
      if user.email_address == email && pswords_match
        matching_users << user
      end
    end

    return matching_users[0]
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    pword = Password.create(password)
    self.password_digest = pword
    @password = password
  end

  def is_password?(password)
    db_password = Password.new(self.password_digest)
    db_password == password
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logout!(user)
    @current_user = nil
    session[:session_token] = nil
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render action: 'new'
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def index
    @bands = Band.all
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index

  end
  def new

  end

  def create
    @user = User.find_by_credentials(*params["user"].values)
    if @user != nil
      login!(@user)
      redirect_to "http://localhost:3000/users/#{@user.id}"
    else
      flash[:notice] = "invalid password or username"
      redirect_to "http://localhost:3000/sessions"
    end
  end

  def destroy
    logout!(current_user)
    redirect_to users_url
  end

  def show
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.permit(:email_address, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to users_url
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    logout!(@user)
    @user.destroy
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email_address, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/index.html.erb
<h1>Bands! Bands! Bands!</h1>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Band', new_band_path %>
<%= link_to 'log_in', "http://localhost:3000/sessions" %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<form action="<%= bands_url %>" method="POST">

  <input
  	     name="authenticity_token"
  	     type="hidden"
  	     value="<%= form_authenticity_token %>">


  <label for "band_name">band name </label>
  <input type = "text" name = "band[name]" id = "band_name">

  <input type="submit" value="Submit">
</form>

<%= link_to 'Back', bands_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if current_user != nil %>
  <%= "hello #{current_user.email_address}" %>
<% end %>
<%= yield %>

<% if current_user != nil %>
  <%= button_to "Logout", sessions_url, method: :delete %>
<% end %>
</body>
</html>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email_address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'log_in', "http://localhost:3000/sessions" %>

app/views/users/new.html.erb
<h1>New user</h1>

<form action="<%= users_url %>" method="POST">

  <input
  	     name="authenticity_token"
  	     type="hidden"
  	     value="<%= form_authenticity_token %>">


  <label for "email_address">email address </label>
  <input type = "text" name = "user[email_address]" id = "email_address">

	<label for="password"> Password</label>
	<input type="password" name="user[password]" id="password">

  <input type="submit" value="Submit">
</form>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>